### ISSUE TITLE
measure surface "roughness"

### ISSUE THREAD

**Issue by kkiesling** [svalinn/dagmc_stats#40]
It would be beneficial to determine the surface "roughness" in a geometry. This could be some characteristic value for each surface or a value that is tagged on each triangle to create essentially a heat map of roughness. There seems to be many different ways to calculate roughness of a 3D mesh, so more research is needed to determine what is most beneficial and the correct way to calculate for our needs.

**Comment by kkiesling** [comment]
After some literature review with @yqin43, [this paper](https://www.sciencedirect.com/science/article/pii/S0097849312001203#f0020) looks to be the most promising and easiest way to measure roughness. Equation 5 will get us the local roughness value for each facet.

As far as usable output, I have two thoughts:

1. Output list of local roughness values (can be per surface, per volume, or whole geometry) - just like we do already with other stats.
2. Tag the geometry with LR values on each facet and write out the geometry file again.

**Comment by kkiesling** [comment]
Tagging the geometry file and writing the file out again brings up the question of whether we want this DAGMC Stats tool to be manipulating geometry files like that. @gonuke do you have any thoughts about whether this tool should be used for this type of thing?

**Comment by gonuke** [comment]
It could be a user option to either tag nothing or tag some standard set of metrics.  Definitely not a user option to turn on/off tagging of different quantities independently.

**Comment by gonuke** [comment]
Effectively completed by #66, now pending class refactor
