### ISSUE TITLE
Update get_triangles_per_surface for new design

### ISSUE THREAD

**Issue by yqin43** [svalinn/dagmc_stats#92]

**Comment by gonuke** [comment]
How does this method fit into the new design?  The current design already get all the triangles for all the surfaces in the meshset that is used to setup the `DagmcQuery` object.  What's the use case that we are missing and how would it work?

**Comment by gonuke** [comment]
Maybe a related question... is this a method of `DagmcFile` or `DagmcQuery` in our current design?

**Comment by yqin43** [comment]
> How does this method fit into the new design? The current design already get all the triangles for all the surfaces in the meshset that is used to setup the `DagmcQuery` object. What's the use case that we are missing and how would it work?
This function was in the original dagmc_stats.py file when I took over this work. It calculates the number of triangles of each surface instead of getting the triangles. 
I think it should be put into the DagmcQuery function.
